// This file was auto-generated by Fern from our API Definition.

package game

import (
	uuid "github.com/gofrs/uuid/v5"
	rivetgo "github.com/rivet-gg/rivet-go"
)

type Handle struct {
	GameId      uuid.UUID           `json:"game_id"`
	NameId      rivetgo.Identifier  `json:"name_id"`
	DisplayName rivetgo.DisplayName `json:"display_name"`
	// The URL of this game's logo image.
	LogoUrl *string `json:"logo_url,omitempty"`
	// The URL of this game's banner image.
	BannerUrl *string `json:"banner_url,omitempty"`
}
